Update workflow_3.yml

diff --git a/.github/workflows/workflow_3.yml b/.github/workflows/workflow_3.yml
--- a/.github/workflows/workflow_3.yml
+++ b/.github/workflows/workflow_3.yml
@@ -3,12 +3,11 @@ name: Build & Deploy Docker Image - 3
 # Controls when the workflow will run
 on:
   workflow_dispatch:
-    branches:
-      - main
-    
-  push:
-    branches:
-      - dev
+    # inputs:
+    #   image_tag:
+    #     description: 'Docker image tag. Use your story number. Example: US373172. DO NOT USE `dev` tag.'
+    #     required: true
+    #     type: string
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
@@ -16,6 +15,8 @@ jobs:
   checkout-repo:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
+    env:
+      AUTHORIZED_USERS: "LakshanyaP rsures98"
 
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
@@ -32,30 +33,24 @@ jobs:
           GITHUB_CONTEXT: ${{ toJson(github) }}
         run: |
           echo "$GITHUB_CONTEXT"
+
+      - name: Fail if user is not authorised
+        if: ${{ !contains('${{ env.AUTHORIZED_USERS }}', github.actor) }}
+        run: |
+          echo "Only authorized users can trigger the workflow."
+          exit 1
         
-  build-and-deploy-dev:
-    runs-on: ubuntu-latest
-    needs: checkout-repo
-    if: github.ref_name == 'dev'
-    steps:
-      - name: Build Docker image - DEV
-        run: |
-          echo Building Docker Image for DEV environment      
+      # - name: Build Docker image - DEV
+      #   if: github.ref_name == 'dev' && github.event_name == 'push'
+      #   run: |
+      #     echo Building Docker Image for DEV environment      
+         
+      # - name: Build Docker image - STG
+      #   if: github.ref_name == 'main' && github.event_name == 'workflow_dispatch'
+      #   run: |
+      #     echo Building Docker Image for STG environment
 
-  build-and-deploy-stg:
-    runs-on: ubuntu-latest
-    if: github.ref_name == 'main' && github.event_name == 'workflow_dispatch'
-    needs: checkout-repo
-    steps:       
-      - name: Build Docker image - STG
-        run: |
-          echo Building Docker Image for STG environment
-
-  build-and-deploy-prod:
-    runs-on: ubuntu-latest
-    if: github.ref_name == 'main'
-    needs: build-and-deploy-stg
-    steps:       
-      - name: Build Docker image - PROD
-        run: |
-          echo Building Docker Image for PROD environment
+      # - name: Build Docker image - PROD
+      #   if: github.ref_name == 'main' && github.event_name == 'workflow_dispatch'
+      #   run: |
+      #     echo Building Docker Image for PROD environment
